services:
  db:
    image: postgres:16-alpine
    container_name: vssa-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: vssa12345
      POSTGRES_DB: vssa
    ports:
      - "5432:5432"
    volumes:
      - vssa_pgdata:/var/lib/postgresql/data

volumes:
  vssa_pgdata: